import time

from ...version import __version__
from . import jer


SOURCE_FMT = '''\
//! This file was generated by asn1tools version {version} {date}.

{helpers}
{types_code}\
'''


def generate(compiled, codec):
    """Generate Dart source code from given compiled specification.

    """

    date = time.ctime()

    if codec == 'jer':
        helpers, types_code = jer.generate(compiled)
    else:
        raise Exception()

    source = SOURCE_FMT.format(version=__version__,
                               date=date,
                               helpers=helpers,
                               types_code=types_code)

    return source
